include ../Makefile.mk

build:	runninglight.lst runninglight.srec runninglight.hex runninglight.ascii_hex runninglight.bin \
		runninglight.srec.dis runninglight.mif.dis runninglight.hex.dis runninglight.ascii_hex.dis runninglight.bin.dis

