include ../Makefile.mk

build: 1d-conways-gol.lst 1d-conways-gol.srec 1d-conways-gol.hex 1d-conways-gol.bin 1d-conways-gol.srec.dis 1d-conways-gol.mif.dis 1d-conways-gol.hex.dis 1d-conways-gol.bin.dis

