include ../Makefile.mk

build:	org.lst org.srec org.hex org.ascii_hex org.bin \
		org.srec.dis org.mif.dis org.hex.dis org.ascii_hex.dis org.bin.dis \
		equ.lst equ.srec equ.hex equ.ascii_hex equ.bin \
		equ.srec.dis equ.mif.dis equ.hex.dis equ.ascii_hex.dis equ.bin.dis

