include ../Makefile.mk

build:	rtn_nopf.lst rtn_nopf.srec rtn_nopf.hex rtn_nopf.bin \
 		rtn_nopf.srec.dis rtn_nopf.mif.dis rtn_nopf.hex.dis rtn_nopf.bin.dis \
 		rtn_nopo.lst rtn_nopo.srec rtn_nopo.hex rtn_nopo.bin \
 		rtn_nopo.srec.dis rtn_nopo.mif.dis rtn_nopo.hex.dis rtn_nopo.bin.dis \
 		rtn_jsr.lst rtn_jsr.srec rtn_jsr.hex rtn_jsr.bin \
 		rtn_jsr.srec.dis rtn_jsr.mif.dis rtn_jsr.hex.dis rtn_jsr.bin.dis
