include ../Makefile.mk

build:	to-gray.lst to-gray.srec to-gray.hex to-gray.ascii_hex to-gray.bin \
		to-gray.srec.dis to-gray.mif.dis to-gray.hex.dis to-gray.ascii_hex.dis to-gray.bin.dis \
		from-gray.lst from-gray.srec from-gray.hex from-gray.ascii_hex from-gray.bin \
		from-gray.srec.dis from-gray.mif.dis from-gray.hex.dis from-gray.ascii_hex.dis from-gray.bin.dis
