include ../Makefile.mk

build: 	4-bit-comparator.lst 4-bit-comparator.srec 4-bit-comparator.hex 4-bit-comparator.ascii_hex 4-bit-comparator.bin \
 		4-bit-comparator.srec.dis 4-bit-comparator.mif.dis 4-bit-comparator.hex.dis 4-bit-comparator.ascii_hex.dis \
 		4-bit-comparator.bin.dis

