include ../Makefile.mk

build:	selftest.lst selftest.srec selftest.hex selftest.ascii_hex selftest.bin \
		selftest.srec.dis selftest.mif.dis selftest.hex.dis selftest.ascii_hex.dis selftest.bin.dis

