include ../Makefile.mk

build:	killthebit.lst killthebit.srec killthebit.hex killthebit.ascii_hex killthebit.bin \
		killthebit.srec.dis killthebit.mif.dis killthebit.hex.dis killthebit.ascii_hex.dis killthebit.bin.dis

