include ../Makefile.mk

build: 	4-bit-adder.lst 4-bit-adder.srec 4-bit-adder.hex 4-bit-adder.ascii_hex 4-bit-adder.bin \
		4-bit-adder.srec.dis 4-bit-adder.mif.dis 4-bit-adder.hex.dis 4-bit-adder.ascii_hex.dis 4-bit-adder.bin.dis

