include ../Makefile.mk

build: 	palindrome.lst palindrome.srec palindrome.hex palindrome.ascii_hex palindrome.bin \
		palindrome.srec.dis palindrome.mif.dis palindrome.hex.dis palindrome.ascii_hex.dis palindrome.bin.dis
