include ../Makefile.mk

build:	build_cw_wave build_ccw_wave \
		build_cw_full_step build_ccw_full_step \
		build_cw_half_step build_ccw_half_step


build_cw_wave:	cw_wave.lst cw_wave.srec cw_wave.hex cw_wave.bin \
				cw_wave.srec.dis cw_wave.mif.dis cw_wave.hex.dis cw_wave.bin.dis


build_cw_full_step:	cw_full_step.lst cw_full_step.srec cw_full_step.hex cw_full_step.bin \
					cw_full_step.srec.dis cw_full_step.mif.dis cw_full_step.hex.dis cw_full_step.bin.dis

build_cw_half_step:	cw_half_step.lst cw_half_step.srec cw_half_step.hex cw_half_step.bin \
					cw_half_step.srec.dis cw_half_step.mif.dis cw_half_step.hex.dis cw_half_step.bin.dis

build_ccw_wave:	ccw_wave.lst ccw_wave.srec ccw_wave.hex ccw_wave.bin \
				ccw_wave.srec.dis ccw_wave.mif.dis ccw_wave.hex.dis ccw_wave.bin.dis

build_ccw_full_step:	ccw_full_step.lst ccw_full_step.srec ccw_full_step.hex ccw_full_step.bin \
						ccw_full_step.srec.dis ccw_full_step.mif.dis ccw_full_step.hex.dis ccw_full_step.bin.dis

build_ccw_half_step:	ccw_half_step.lst ccw_half_step.srec ccw_half_step.hex ccw_half_step.bin \
						ccw_half_step.srec.dis ccw_half_step.mif.dis ccw_half_step.hex.dis ccw_half_step.bin.dis
