include ../Makefile.mk

build:	4-bit-d-flip-flop.lst 4-bit-d-flip-flop.mif 4-bit-d-flip-flop.srec 4-bit-d-flip-flop.hex 4-bit-d-flip-flop.ascii_hex 4-bit-d-flip-flop.bin \
		4-bit-d-flip-flop.srec.dis 4-bit-d-flip-flop.mif.dis 4-bit-d-flip-flop.hex.dis 4-bit-d-flip-flop.ascii_hex.dis 4-bit-d-flip-flop.bin.dis \
		4-bit-latch.lst 4-bit-latch.mif 4-bit-latch.srec 4-bit-latch.hex 4-bit-latch.ascii_hex 4-bit-latch.bin \
		4-bit-latch.srec.dis 4-bit-latch.mif.dis 4-bit-latch.hex.dis 4-bit-latch.ascii_hex.dis 4-bit-d-flip-flop.bin.dis \
		1-bit-sr-latch.lst 1-bit-sr-latch.mif 1-bit-sr-latch.srec 1-bit-sr-latch.hex 1-bit-sr-latch.ascii_hex 1-bit-sr-latch.bin \
		1-bit-sr-latch.srec.dis 1-bit-sr-latch.mif.dis 1-bit-sr-latch.hex.dis 1-bit-sr-latch.ascii_hex.dis 1-bit-sr-latch.bin.dis \
		1-bit-jk-flip-flop.lst 1-bit-jk-flip-flop.mif 1-bit-jk-flip-flop.srec 1-bit-jk-flip-flop.hex 1-bit-jk-flip-flop.ascii_hex 1-bit-jk-flip-flop.bin \
		1-bit-jk-flip-flop.srec.dis 1-bit-jk-flip-flop.mif.dis 1-bit-jk-flip-flop.hex.dis 1-bit-jk-flip-flop.ascii_hex.dis 1-bit-jk-flip-flop.bin.dis

